-- caffeine = hs.menubar.new()
-- caffeine:setTitle("HELLO")
-- caffeine:setTooltip("FUCK")
-- local function caffeineClicked() hs.alert.show("FUCK") end
-- caffeine:setClickCallback(caffeineClicked)
